#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.101.100:3306/airline_ticket?useSSL=false&useunicode=true&characterEncoding=utf8
#    username: hive
#    password: admin

#连接本地数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/airline_ticket?serverTimezone=UTC
    username: root
    password: 105036
  jpa:
    hibernate:
      #设置自动更新实体类到数据库中，在开发时可以设置为update但在上线使用时更改为none
      ddl-auto: none
    show-sql: true

#swagger开关
switch-swagger-up: true

#csv文件路径
csv-path: "D:/部分文件/课程内容/实习/文档/ticket1.csv"